version: "3.7"

services:
  backend:
    image: willy874/nothing-accounting-backend:$docker_image_tag
    command: >
      sh -c "npx prisma migrate dev && npx prisma db seed && npm run server"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    env_file: .env
  
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: accounting_dev
    networks:
      - backend

networks:
  backend:
