---

- name: pull code repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dir }}"
    update: yes
    version: "{{ branch }}"

- name: docker-compose down
  command: docker-compose down
  args:
    chdir: "{{ repo_dir }}"
  ignore_errors: yes

- name: docker-compose up
  command: docker-compose -f docker-compose.yaml -f docker-compose.production.yaml
  args:
    chdir: "{{ repo_dir }}"